apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=        # "postgres" em Base64
  POSTGRES_PASSWORD: c2VuaGE=        # "senha" em Base64
  POSTGRES_DB: bXlkYg==              # "mydb" em Base64
